# Generated by Django 5.2.4 on 2025-07-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_cover_book_text_author_alter_book_text_book_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="text_book",
        ),
    ]
