# Generated by Django 5.2.4 on 2025-07-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0005_book_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="slug",
        ),
    ]
