# Generated by Django 5.2.4 on 2025-07-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_book_slug"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bookquote",
            old_name="quote",
            new_name="text",
        ),
    ]
